name: Playit Static
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
    - name: Setup
      run: |
        net user myuser MyNewPass123! /add
        net localgroup administrators myuser /add
        Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
        Start-Service sshd
        curl -sSL -o playit.exe https://playit.gg/playit-windows-amd64.exe
        .\playit.exe -k "YOUR_PLAYIT_TOKEN" -s
