name: RDP
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Start RDP via zrok
      run: |
        net user myuser MyNewPass123! /add
        net localgroup administrators myuser /add
        curl -sSL -o zrok.zip https://github.com/openziti/zrok/releases/latest/download/zrok_windows_amd64.zip
        unzip -o zrok.zip
        .\zrok.exe share public tcp:3389
        while ($true) { Start-Sleep -Seconds 60 }
